apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-deployment1"
  labels:
   app: "nginx"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx"
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - name: "webserver1"
        image: "nginx:1.6"
        portS:
          - containerPort:"80"        
      - name: "database-server"
        image: "mysql-3.2"
        portS:
          - containerPort: "3306"
